### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Team-W456** [PhilippThoelke/eeg-transformer#1]
Hello,  sorry to bother you, I am  very interested in your research, while running the  download_data.py file, there is an  error ：FileNotFoundError: [Errno 2] No such file or directory: 'data/raw-nsamp_25614-eplen_320-example_all.dat'，so how to solve it?  I would be very grateful if you could reply me.

**Comment by dav0dea** [comment]
Hi, thank you for your interest in the package! Did you make sure to create the `data/` directory before running the script?

**Comment by Team-W456** [comment]
> Hi, thank you for your interest in the package! Did you make sure to create the `data/` directory before running the script?

Wow, thank you for your reply. After creating the **data/** as you said, the file is indeed downloaded with the script, but why do I still get the previous error  when I run the download_data.py  file directly?

**Comment by dav0dea** [comment]
The download_data.py script assumes that the directory exists and doesn't create it if it's not present. The code currently doesn't handle failure cases very well as I only developed it for [this](https://doi.org/10.32470/CCN.2022.1240-0) project so far. This is definitely not a production ready framework and is more meant as a research codebase.

**Comment by Team-W456** [comment]
> 
Thank you for your reply in your busy schedule, I will continue to study.

**Comment by Team-W456** [comment]
> The download_data.py script assumes that the directory exists and doesn't create it if it's not present. The code currently doesn't handle failure cases very well as I only developed it for [this](https://doi.org/10.32470/CCN.2022.1240-0) project so far. This is definitely not a production ready framework and is more meant as a research codebase.

Thank you for your reply in your busy schedule, I will continue to study.
