### ISSUE TITLE
Error while training the dataset

### ISSUE THREAD

**Issue by AngsumanGoswami** [PhilippThoelke/eeg-transformer#2]
Hi, Sorry to bother you. I was working on a project and was trying to build the code you have in this repo. While doing that I found that the training part is throwing an error. 
ERROR : 
  File "<string>", line 1, in <module>
  File "C:\Users\angsu\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\angsu\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

If you kindly have a look and let me know how to solve then it will be helpfully. Thanks in advance.

**Comment by dav0dea** [comment]
Hi, it is difficult to pinpoint the problem without further details. Could you elaborate on how you achieved this error? I.e. what did you run, with which parameters? Please also indicate the `torch` and `pytorch-lightning` versions in your local environment.
